# Generated by Django 6.0.5 on 2026-05-26 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todosapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="criacao",
            new_name="data_criacao",
        ),
        migrations.RenameField(
            model_name="todo",
            old_name="data",
            new_name="data_entrega",
        ),
    ]
