# Generated by Django 6.0.5 on 2026-05-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todosapp", "0002_rename_criacao_todo_data_criacao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="data_entrega",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="todo",
            name="datafinal",
            field=models.DateField(null=True),
        ),
    ]
